name: Check Markdown links

on: 
  push:
    branches:
    - master
    paths-ignore:
      - '.github/**'
  schedule:
  # Run everyday at 9:00 AM (See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07)
  - cron: "0 9 * * *"

jobs:

  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        config-file: './.github/workflows/mlc_config.json'

  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v17
      with:
        globs: |
          CODE_OF_CONDUCT.md
          README.md
          contributing.md
